#!/bin/sh 
echo "Source file validation..."

sed -e '1,/^exit$/d' -e '/^rootfs-tag/,$d' "$0" | gzip -t -
err_chk=$?
if [ $err_chk -ne 1 ]; then
	echo "Upgrading kernel image..."
	/etc/init.d/br_wifi stop > /dev/null
	/etc/init.d/samba stop > /dev/null
	/usr/bin/killall -9 MonitorWan
	/bin/kill -s USR1 `cat /tmp/lock/brlcd.lock`
	/usr/bin/killall bandluxed
	/usr/bin/killall BatteryMonitor
	/usr/bin/killall crond
	/usr/bin/killall udhcpd
	/usr/bin/killall klogd
	/usr/bin/killall syslogd
	/bin/umount /data
	/bin/umount /mnt
	sync
	sync
	mtd erase mtd2
	sed -e '1,/^exit$/d' -e '/^rootfs-tag/,$d' "$0" | tar xzOf - | mtd write - mtd2
	echo "..."
	sync
else
	echo "Fail to decompress kernel image!"    
fi

sync
sleep 3

echo "..."
sed -e '1,/^rootfs-tag/d' "$0" | gzip -t -
err_chk=$?
if [ $err_chk -ne 1 ]; then
	echo "Upgrading rootfs..."
	sync
	mount -o remount,ro /
	mtd erase mtd3
	sed -e '1,/^rootfs-tag/d' "$0" | tar xzOf - | mtd write - mtd3
	echo "...Upgrade Finish"
	echo "System will reboot..."
	sync
	sync
	sync
	sleep 5
	reboot -f
else
	echo "Fail to decompress rootfs image!"
fi

exit
