#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <errno.h>
#include <unistd.h>
#include <syslog.h>
#include <string.h>
#include <signal.h>
#include <fcntl.h>
#include <linux/fb.h>
#include <sys/mman.h>
#include <sys/ioctl.h>
#include <linux/input.h>
#include <pthread.h>
#include <sys/ipc.h>
#include <sys/shm.h>
#include <linux/Bandrich/sharememory.h>
#include "status_bar.h"
#include "OLED_DRAW_API.h"
#include "br_define.h"
#define HOSTAPD_CTRL_INTERFACE ("/tmp/tiwlan0")
#define HOSTAPD_DEFAULT_CONF_FILE_PATH ("/userdata/default/config")
#define HOSTAPD_UCI_CMD_MAX_LEN (256)
#define WPS_DFLT_AUTH_AUTH_TYPE	("wpa")
#define WPS_DFLT_WPA_WPA_USEKEY ("passphrase")
#define WPS_DFLT_WPA_PSK	("")
#define WPS_DFLT_WPA_PASSPHRASE	("bandrich")
#define WPS_DFLT_WPA_PAIRWISE	("TKIP CCMP")
#include "wpa_ctrl.h"
#include "ucimap.h"
#include <stdarg.h>
#define WPA_USEKEY_MAX_LEN	(10)	// strlen("passphrase")
#define WPA_PSK_MAX_LEN		(64)
#define WPA_PASSPHRASE_MAX_LEN	(63)
#define WPA_PAIRWISE_MAX_LEN	(9)	// strlen("TKIP CCMP")
typedef struct wpa_info_s{char wpa_usekey[WPA_USEKEY_MAX_LEN+1];char wpa_psk[WPA_PSK_MAX_LEN+1];char wpa_passphrase[WPA_PASSPHRASE_MAX_LEN+1];char wpa_pairwise[WPA_PAIRWISE_MAX_LEN+1];}wpa_info_s_type;
#define RUNNING_DIR	"/userdata/brlcd"
#define LOCK_FILE	"/var/lock/brlcd.lock"
#define LOG_FILE	"/var/log/brlcd.log"
#define DEVICE_NAME	"/dev/fb0"
#define DEFAULT_LCD_W		128
#define DEFAULT_LCD_H		64
#define DEFAULT_LANG	"en.txt"
#define MAX_TEXT_LEN	512
#define WPS_ENABLE_COUNT_TIME	5
char dot_matrix[DEFAULT_LCD_W][DEFAULT_LCD_H];int fbfd=0;char*fbp=0;long screensize=0;int key_fd;static int g_screen_id;static int g_isRunUpdate;static int g_wps_enable_time=WPS_ENABLE_COUNT_TIME;static int g_reset_to_default_time=10;static int g_lcd_dim_half=10;static int g_lcd_off=5;static int g_isCountToStartWPS=0;static int g_isStartResetToDefault=0;static int g_isShowWPSSuccess=0;static int g_isWiFiSwitch=0;static int g_isUpdatingFW=0;static all_info_t*all_info=NULL;int shm_fd;void*shared_memory=(void*)0;static char g_pr_version[15]={0};static int g_isStartAutoWiFiOff=0;static int g_AutoWiFiOffCount=0;static char g_isSleepMode=0;void log_message(filename,message)char*filename;char*message;{FILE*logfile;logfile=fopen(filename,"a");if(!logfile)return;fprintf(logfile,"%s\n",message);
fclose(logfile);}int memory_close(void){if(shmdt(shared_memory)==-1){fprintf(stderr,"shmdt failed\n");exit(EXIT_FAILURE);}free(all_info);all_info=NULL;return errno;}void showFWUpdate();void signal_handler(sig)int sig;{switch(sig){case SIGUSR1:g_isRunUpdate=0;reset_bar();showFWUpdate();sem_post(&g_update_sem);break;case SIGUSR2:g_isStartAutoWiFiOff=1;g_AutoWiFiOffCount=0;log_message(LOG_FILE,"SIGUSR2 signal catched(wifi)");sem_post(&g_timer_sem);break;case SIGHUP:log_message(LOG_FILE,"hangup signal catched");break;case SIGTERM:log_message(LOG_FILE,"terminate signal catched");g_isRunUpdate=0;sem_post(&g_update_sem);break;}}void daemonize(){int i,lfp;char str[10];if(getppid()==1)return;i=fork();if(i<0)exit(1);if(i>0)exit(0);setsid();for(i=getdtablesize();i>=0;--i)close(i);i=open("/dev/null",
O_RDWR);dup(i);dup(i);umask(027);chdir(RUNNING_DIR);lfp=open(LOCK_FILE,O_RDWR|O_CREAT,0640);if(lfp<0)exit(1);if(lockf(lfp,F_TLOCK,0)<0)exit(0);sprintf(str,"%d\n",getpid());write(lfp,str,strlen(str));signal(SIGCHLD,SIG_IGN);signal(SIGTSTP,SIG_IGN);signal(SIGTTOU,SIG_IGN);signal(SIGTTIN,SIG_IGN);signal(SIGHUP,signal_handler);signal(SIGTERM,signal_handler);signal(SIGUSR1,signal_handler);signal(SIGUSR2,signal_handler);}void initLCD(){struct fb_var_screeninfo vinfo;struct fb_fix_screeninfo finfo;int choice=0,line_width=1;unsigned x,y;unsigned location,value1,value2;fbfd=open(DEVICE_NAME,O_RDWR);if(fbfd<0){printf("Error: cannot open %s.\n",DEVICE_NAME);exit(0);}printf("%s:was opened successfully.\n",DEVICE_NAME);if(ioctl(fbfd,FBIOGET_FSCREENINFO,&finfo)){printf(
"%s:Error reading fixed information.\n",DEVICE_NAME);exit(0);}if(ioctl(fbfd,FBIOGET_VSCREENINFO,&vinfo)){printf("%s:Error reading variable information.\n",DEVICE_NAME);exit(0);}printf("smem_len:%d\n",finfo.smem_len);printf("line_length:%d\n",finfo.line_length);printf("xres:%d\n",vinfo.xres);printf("yres:%d\n",vinfo.yres);printf("bits_per_pixel:%d\n",vinfo.bits_per_pixel);screensize=vinfo.xres*vinfo.yres*vinfo.bits_per_pixel/8;fbp=(char*)mmap(0,screensize,PROT_READ|PROT_WRITE,MAP_SHARED,fbfd,0);if((int)fbp==-1){printf("%s:Error: failed to map framebuffer device to memory.\n",DEVICE_NAME);exit(0);}int iy;printf("%s:The framebuffer device was mapped to memory successfully.\n",DEVICE_NAME);system("echo 0 > /sys/class/graphics/fb0/blank");system(
"echo 128 > /sys/class/backlight/mxc_slcdc_bl.0/brightness");}void drawfb(){unsigned int location=0,x,y;for(y=0;y<DEFAULT_LCD_H;y++){for(x=0;x<DEFAULT_LCD_W;x++){*(fbp+location)=dot_matrix[x][y];location++;}}}void initTextArea(){int iy;for(iy=21;iy<DEFAULT_LCD_H;iy++){int ix;for(ix=0;ix<DEFAULT_LCD_W;ix++)dot_matrix[ix][iy]=0;}}void getStringLine(char*_filename,char*_key,char*_outbuf){FILE*fp;char inbuf[MAX_TEXT_LEN];char*keystr,*valstr;char*strtok_data=NULL;strcpy(_outbuf,_key);fp=fopen(_filename,"r");if(fp==NULL){log_message(LOG_FILE,"open lang file fail.\n");return;}while(fgets(inbuf,MAX_TEXT_LEN,fp)!=NULL){keystr=strtok_r(inbuf,"=",&strtok_data);if(keystr[0]=='#'||strcmp(keystr,_key)!=0)continue;valstr=strtok_r(NULL,"=",&strtok_data);strcpy(_outbuf,valstr);int len=strlen(valstr);if(
valstr[len-1]=='\n'){valstr[len-1]='\0';len=strlen(valstr);}break;}fclose(fp);}void drawLine1(char*_msg){char outbuf[MAX_TEXT_LEN];initTextArea();getStringLine(DEFAULT_LANG,_msg,outbuf);Draw_string_line1(outbuf,18);drawfb();}int get_input_event_handle(char name[]){int i,len,name_len;int event_handle=-1,fd;char cmd_buf[50];if(name==NULL)return-1;name_len=strlen(name);for(i=0;i<2;i++){sprintf(cmd_buf,"/sys/class/input/input%d/name",i);fd=open(cmd_buf,O_RDONLY);if(fd>0){if((len=read(fd,(void*)cmd_buf,name_len))>0){cmd_buf[len]='\x0';if(!strncmp(cmd_buf,name,name_len)){event_handle=i;}}}close(fd);if(event_handle>=0)break;}fd=-1;if(event_handle>=0){sprintf(cmd_buf,"/dev/input/event%d",event_handle);printf("input dev: %s\r\n",cmd_buf);key_fd=open(cmd_buf,O_RDONLY);fd=key_fd;}return fd;}void 
initKeyEvent(){if(get_input_event_handle("gpio-keys")<0){log_message(LOG_FILE,"Can not open key event device.");}}int getKeyEvent(struct input_event*_ev){int nBytes;nBytes=read(key_fd,(char*)_ev,sizeof(struct input_event));return nBytes;}void initLCDTime(){g_lcd_dim_half=10;g_lcd_off=5;}void keyevent_task(void*arg){struct input_event ev;char tmp[128];int ret;while(g_isRunUpdate){ret=getKeyEvent(&ev);if(ev.type==EV_KEY){if(ev.type==EV_KEY&&ev.value==1&&ev.code==KEY_WAKEUP){g_isSleepMode=0;sem_post(&g_timer_sem);sem_post(&g_update_sem);continue;}if(g_lcd_dim_half==-1&&g_lcd_off==-1){system("echo 0 > /sys/class/graphics/fb0/blank");system("echo 128 > /sys/class/backlight/mxc_slcdc_bl.0/brightness");initLCDTime();if(ev.type==EV_KEY&&ev.code!=KEY_SLEEP){sem_post(&g_timer_sem);sem_post(&
g_update_sem);continue;}}if(g_lcd_dim_half==-1){system("echo 128 > /sys/class/backlight/mxc_slcdc_bl.0/brightness");initLCDTime();if(ev.type==EV_KEY)continue;}if(all_info->u_threeG_info.PIN_status!=PIN_READY&&ev.code!=KEY_SLEEP)continue;if(ev.type==EV_KEY&&ev.value==1&&ev.code==0x101){g_isStartResetToDefault++;g_AutoWiFiOffCount=0;if(g_isStartResetToDefault<2){if(g_screen_id!=BR_WPS_Fun)g_screen_id++;else g_screen_id=BR_BASIC;g_isShowWPSSuccess=0;sem_post(&g_update_sem);}else if(g_isCountToStartWPS==1){g_isCountToStartWPS=0;g_wps_enable_time=WPS_ENABLE_COUNT_TIME;}}else if(ev.type==EV_KEY&&ev.value==1&&ev.code==0x100){g_isStartResetToDefault++;g_AutoWiFiOffCount=0;if(g_isStartResetToDefault<2){if(g_wps_enable_time!=0)g_isCountToStartWPS=1;g_isShowWPSSuccess=0;sem_post(&g_update_sem);}}
else if(ev.type==EV_KEY&&ev.value==1&&ev.code==KEY_SLEEP){if(g_AutoWiFiOffCount>=all_info->u_wifi.sleep_time&&all_info->u_wifi.wifi_auto_off==wifi_auto_off_on&&getAllowSleepMode()==1){reset_bar();drawLine1("Sleeping...Zzz");g_AutoWiFiOffCount=0;g_isStartAutoWiFiOff=0;log_message(LOG_FILE,"Entering doze...");g_isSleepMode=1;system("/etc/enter_doze.sh");log_message(LOG_FILE,"Wake up...");system("/etc/exit_doze.sh");g_isSleepMode=0;sem_post(&g_timer_sem);}}else if(ev.type==EV_KEY&&ev.value==0&&ev.code==0x100){if(g_isStartResetToDefault>0){--g_isStartResetToDefault;g_reset_to_default_time=10;}if(g_isCountToStartWPS==1){g_isCountToStartWPS=0;if(g_wps_enable_time!=0){g_wps_enable_time=WPS_ENABLE_COUNT_TIME;g_isWiFiSwitch=1;sem_post(&g_update_sem);}}}else if(ev.type==EV_KEY&&ev.value==0&&ev.code
==0x101){if(g_isStartResetToDefault>0){--g_isStartResetToDefault;g_reset_to_default_time=10;}}else if(ev.type==EV_PWR&&ev.value==1){}else if(ev.type==EV_PWR&&ev.value==0){}memset(tmp,0,128);sprintf(tmp,"key type=0x%x,value =%d,code=0x%x,%ld(s)%ld(us)",ev.type,ev.value,ev.code,ev.time.tv_sec,ev.time.tv_usec);printf("key type=0x%x,value =%d,code=0x%x,%ld(s)%ld(us)\n",ev.type,ev.value,ev.code,ev.time.tv_sec,ev.time.tv_usec);initLCDTime();}}}void showFWUpdate(){g_isUpdatingFW=1;drawLine1("FW Updating..");system("echo 0 > /sys/class/graphics/fb0/blank");system("echo 128 > /sys/class/backlight/mxc_slcdc_bl.0/brightness");}int getAllowSleepMode(){FILE*pp;char tmp[2]={0};if((pp=popen("cat /sys/devices/platform/fsl-usb2-udc/gadget/allow_sleep","r"))==NULL){printf("popen() error!\n");pclose(pp);
return;}fgets(tmp,2,pp);pclose(pp);if(strcmp(tmp,"1")==0)return 1;else return 0;}void Timer_handle(void*arg){int _shutdown_count=15;char tmp[32];while(g_isRunUpdate){if(g_lcd_dim_half>0){--g_lcd_dim_half;}if(g_lcd_dim_half<=0&&g_lcd_off>=0){if(g_lcd_dim_half==0){printf("TIMEOUT - LCD DIM HALF\n");system("echo 0 > /sys/class/backlight/mxc_slcdc_bl.0/brightness");--g_lcd_dim_half;}if(g_lcd_off>0&&g_lcd_dim_half==-1)--g_lcd_off;else if(g_lcd_off==0){system("echo 1 > /sys/class/graphics/fb0/blank");printf("TIMEOUT - LCD OFF\n");--g_lcd_off;}}if(g_AutoWiFiOffCount>=all_info->u_wifi.sleep_time&&g_lcd_off==-1){log_message(LOG_FILE,"Stop count timer...");sem_wait(&g_timer_sem);log_message(LOG_FILE,"Start count timer...");}if(((g_isStartAutoWiFiOff==1&&all_info->u_wifi.num_sta==0)||all_info->
u_wifi.num_sta==0)&&all_info->u_wifi.wifi_auto_off==wifi_auto_off_on){if(g_AutoWiFiOffCount<all_info->u_wifi.sleep_time)++g_AutoWiFiOffCount;if(g_AutoWiFiOffCount>=all_info->u_wifi.sleep_time){if(getAllowSleepMode()==1){reset_bar();drawLine1("Sleeping...Zzz");g_AutoWiFiOffCount=0;g_isStartAutoWiFiOff=0;g_isSleepMode=1;system("/etc/enter_doze.sh");system("/etc/exit_doze.sh");g_isSleepMode=0;}else if(all_info->u_wifi.active==1){system("/tmp/ap_rm");log_message(LOG_FILE,"WiFi Auto off...");if(g_lcd_off==-1)sem_wait(&g_timer_sem);}}char logmsg[256];sprintf(logmsg,"Doze Count=%d(%d)",g_AutoWiFiOffCount,all_info->u_wifi.sleep_time);log_message(LOG_FILE,logmsg);}else{g_AutoWiFiOffCount=0;g_isStartAutoWiFiOff=0;}if(g_isCountToStartWPS){if(--g_wps_enable_time==0){sem_post(&g_update_sem);sleep(3);
g_isCountToStartWPS=0;}}if(g_isStartResetToDefault>1){if(--g_reset_to_default_time==0){drawLine1("Reset to default");system("/etc/br_default.sh");system("/sbin/reboot -f");g_isRunUpdate=0;}}usleep(1000*1000);}}void initshmem(){int shmid;shmid=shmget((key_t)SHARE_KEY,sizeof(all_info_t),S_IRUSR|S_IRGRP|S_IROTH|IPC_CREAT);if(-1==shmid){fprintf(stderr,"shmget failed\n");log_message(LOG_FILE,"shmget failed\n");exit(EXIT_FAILURE);}shared_memory=shmat(shmid,(void*)0,0);if(shared_memory==(void*)-1){fprintf(stderr,"shmat failed\n");log_message(LOG_FILE,"shmat failed\n");exit(EXIT_FAILURE);}all_info=(all_info_t*)shared_memory;}static void wpa_ctrl_msg_cb(char*msg,size_t len){}static bool wps_uci_is_auth_wep(struct uci_context*uci_ctx_ptr,char*uci_lookup_str){struct uci_ptr ptr;strncpy(
uci_lookup_str,"hostapd.auth.auth_type",HOSTAPD_UCI_CMD_MAX_LEN);uci_lookup_ptr(uci_ctx_ptr,&ptr,uci_lookup_str,true);return(0==strcmp(ptr.o->v.string,"wep"));}static bool wps_uci_is_auth_wpa(struct uci_context*uci_ctx_ptr,char*uci_lookup_str){struct uci_ptr ptr;strncpy(uci_lookup_str,"hostapd.auth.auth_type",HOSTAPD_UCI_CMD_MAX_LEN);uci_lookup_ptr(uci_ctx_ptr,&ptr,uci_lookup_str,true);return((0==strcmp(ptr.o->v.string,"wpa"))||(0==strcmp(ptr.o->v.string,"wpa2"))||(0==strcmp(ptr.o->v.string,"wpa_wpa2")));}static void wps_uci_backup_setting(struct uci_context*uci_ctx_ptr,char*dest_str,char*uci_field_str,size_t field_max_len,char*uci_lookup_str){struct uci_ptr ptr;strncpy(uci_lookup_str,uci_field_str,HOSTAPD_UCI_CMD_MAX_LEN);uci_lookup_ptr(uci_ctx_ptr,&ptr,uci_lookup_str,true);strncpy(
dest_str,ptr.o->v.string,field_max_len);}static void wps_uci_set_value(struct uci_context*uci_ctx_ptr,char*uci_field_str,char*uci_value_str,char*uci_lookup_str){struct uci_ptr ptr;snprintf(uci_lookup_str,HOSTAPD_UCI_CMD_MAX_LEN,"%s=%s",uci_field_str,uci_value_str);uci_lookup_ptr(uci_ctx_ptr,&ptr,uci_lookup_str,true);uci_set(uci_ctx_ptr,&ptr);uci_save(uci_ctx_ptr,ptr.p);}static void wps_uci_set_cur_from_dflt(struct uci_context*cur_ctx_ptr,struct uci_context*dflt_ctx_ptr,char*uci_field_str,char*uci_lookup_str){struct uci_ptr cur_ptr,dflt_ptr;strncpy(uci_lookup_str,uci_field_str,HOSTAPD_UCI_CMD_MAX_LEN);uci_lookup_ptr(dflt_ctx_ptr,&dflt_ptr,uci_lookup_str,true);snprintf(uci_lookup_str,HOSTAPD_UCI_CMD_MAX_LEN,"%s=%s",uci_field_str,dflt_ptr.o->v.string);uci_lookup_ptr(cur_ctx_ptr,&cur_ptr,
uci_lookup_str,true);uci_set(cur_ctx_ptr,&cur_ptr);uci_save(cur_ctx_ptr,cur_ptr.p);}static void wps_uci_commit(struct uci_context*uci_ctx_ptr,char*uci_field_str,char*uci_lookup_str){struct uci_ptr ptr;strncpy(uci_lookup_str,uci_field_str,HOSTAPD_UCI_CMD_MAX_LEN);uci_lookup_ptr(uci_ctx_ptr,&ptr,uci_lookup_str,true);uci_commit(uci_ctx_ptr,&ptr.p,false);uci_unload(uci_ctx_ptr,ptr.p);}static int wps_check_auth_type(wpa_info_s_type*wpa_info_ptr,bool*auth_changed_ptr){int result=-1;char uci_lookup_str[HOSTAPD_UCI_CMD_MAX_LEN];struct uci_context*uci_cur_ctx_ptr=NULL;*auth_changed_ptr=false;if(NULL!=(uci_cur_ctx_ptr=uci_alloc_context())){uci_load_plugins(uci_cur_ctx_ptr,NULL);if(wps_uci_is_auth_wep(uci_cur_ctx_ptr,uci_lookup_str)){struct uci_context*uci_dflt_ctx_ptr=NULL;struct stat file_stat;
log_message(LOG_FILE,"WPS_CTRL: auth is WEP, change to WPA\n");memset(wpa_info_ptr,0,sizeof(wpa_info_s_type));wps_uci_backup_setting(uci_cur_ctx_ptr,wpa_info_ptr->wpa_usekey,"hostapd.wpa.wpa_usekey",WPA_USEKEY_MAX_LEN,uci_lookup_str);wps_uci_backup_setting(uci_cur_ctx_ptr,wpa_info_ptr->wpa_psk,"hostapd.wpa.wpa_psk",WPA_PSK_MAX_LEN,uci_lookup_str);wps_uci_backup_setting(uci_cur_ctx_ptr,wpa_info_ptr->wpa_passphrase,"hostapd.wpa.wpa_passphrase",WPA_PASSPHRASE_MAX_LEN,uci_lookup_str);wps_uci_backup_setting(uci_cur_ctx_ptr,wpa_info_ptr->wpa_pairwise,"hostapd.wpa.wpa_pairwise",WPA_PAIRWISE_MAX_LEN,uci_lookup_str);sprintf(uci_lookup_str,"%s/hostapd",HOSTAPD_DEFAULT_CONF_FILE_PATH);if(0==stat(uci_lookup_str,&file_stat)){if(NULL!=(uci_dflt_ctx_ptr=uci_alloc_context())){uci_load_plugins(
uci_dflt_ctx_ptr,NULL);uci_set_confdir(uci_dflt_ctx_ptr,HOSTAPD_DEFAULT_CONF_FILE_PATH);if(wps_uci_is_auth_wpa(uci_dflt_ctx_ptr,uci_lookup_str)){wps_uci_set_cur_from_dflt(uci_cur_ctx_ptr,uci_dflt_ctx_ptr,"hostapd.auth.auth_type",uci_lookup_str);wps_uci_set_cur_from_dflt(uci_cur_ctx_ptr,uci_dflt_ctx_ptr,"hostapd.wpa.wpa_usekey",uci_lookup_str);wps_uci_set_cur_from_dflt(uci_cur_ctx_ptr,uci_dflt_ctx_ptr,"hostapd.wpa.wpa_psk",uci_lookup_str);wps_uci_set_cur_from_dflt(uci_cur_ctx_ptr,uci_dflt_ctx_ptr,"hostapd.wpa.wpa_passphrase",uci_lookup_str);wps_uci_set_cur_from_dflt(uci_cur_ctx_ptr,uci_dflt_ctx_ptr,"hostapd.wpa.wpa_pairwise",uci_lookup_str);wps_uci_set_value(uci_cur_ctx_ptr,"hostapd.wps.wps_state","2",uci_lookup_str);wps_uci_commit(uci_cur_ctx_ptr,"hostapd",uci_lookup_str);*
auth_changed_ptr=true;result=0;}else{log_message(LOG_FILE,"WPS_CTRL: factory default auth is not WPA\n");}uci_free_context(uci_dflt_ctx_ptr);}else{log_message(LOG_FILE,"WPS_CTRL(%d): cannot allocate uci context\n",__LINE__);}}else{log_message(LOG_FILE,"WPS_CTRL: no default config, use hard-coded values\n");wps_uci_set_value(uci_cur_ctx_ptr,"hostapd.auth.auth_type",WPS_DFLT_AUTH_AUTH_TYPE,uci_lookup_str);wps_uci_set_value(uci_cur_ctx_ptr,"hostapd.wpa.wpa_usekey",WPS_DFLT_WPA_WPA_USEKEY,uci_lookup_str);wps_uci_set_value(uci_cur_ctx_ptr,"hostapd.wpa.wpa_psk",WPS_DFLT_WPA_PSK,uci_lookup_str);wps_uci_set_value(uci_cur_ctx_ptr,"hostapd.wpa.wpa_passphrase",WPS_DFLT_WPA_PASSPHRASE,uci_lookup_str);wps_uci_set_value(uci_cur_ctx_ptr,"hostapd.wpa.wpa_pairwise",WPS_DFLT_WPA_PAIRWISE,uci_lookup_str);
wps_uci_set_value(uci_cur_ctx_ptr,"hostapd.wps.wps_state","2",uci_lookup_str);wps_uci_commit(uci_cur_ctx_ptr,"hostapd",uci_lookup_str);*auth_changed_ptr=true;result=0;}}else{log_message(LOG_FILE,"WPS_CTRL: cur auth is NOT WEP\n");result=0;}uci_free_context(uci_cur_ctx_ptr);}return result;}static void wps_restore_auth_config(wpa_info_s_type*wpa_info_ptr){char uci_lookup_str[HOSTAPD_UCI_CMD_MAX_LEN];struct uci_context*uci_ctx_ptr=NULL;if(NULL!=(uci_ctx_ptr=uci_alloc_context())){uci_load_plugins(uci_ctx_ptr,NULL);wps_uci_set_value(uci_ctx_ptr,"hostapd.auth.auth_type","wep",uci_lookup_str);wps_uci_set_value(uci_ctx_ptr,"hostapd.wpa.wpa_usekey",wpa_info_ptr->wpa_usekey,uci_lookup_str);wps_uci_set_value(uci_ctx_ptr,"hostapd.wpa.wpa_psk",wpa_info_ptr->wpa_psk,uci_lookup_str);wps_uci_set_value(
uci_ctx_ptr,"hostapd.wpa.wpa_passphrase",wpa_info_ptr->wpa_passphrase,uci_lookup_str);wps_uci_set_value(uci_ctx_ptr,"hostapd.wpa.wpa_pairwise",wpa_info_ptr->wpa_pairwise,uci_lookup_str);wps_uci_set_value(uci_ctx_ptr,"hostapd.wps.wps_state","0",uci_lookup_str);wps_uci_commit(uci_ctx_ptr,"hostapd",uci_lookup_str);uci_free_context(uci_ctx_ptr);}}static int wps_start(void){
#define WPS_BUF_SIZE (4096)
struct wpa_ctrl*ctrl_conn=NULL;char buf[WPS_BUF_SIZE];size_t resp_len;int ret;bool exit;wpa_info_s_type wpa_info;bool auth_changed=false;if(0!=wps_check_auth_type(&wpa_info,&auth_changed)){log_message(LOG_FILE,"WPS_CTRL: check auth failed!\n");drawLine1("Failed to activate WPS");sleep(5);return-1;}if(auth_changed){system("/etc/init.d/br_wifi restart");sleep(3);}ctrl_conn=wpa_ctrl_open(HOSTAPD_CTRL_INTERFACE);if(ctrl_conn){}else{log_message(LOG_FILE,"WPS_CTRL: failed to connect to hostapd!");drawLine1("Failed to activate WPS");sleep(5);return-1;}ret=wpa_ctrl_attach(ctrl_conn);if(-2==ret){log_message(LOG_FILE,"WPS_CTRL: attach timeout!");return-2;}else if(-1==ret){log_message(LOG_FILE,"WPS_CTRL: attach error!");return-1;}resp_len=WPS_BUF_SIZE-1;ret=wpa_ctrl_request(ctrl_conn,"WPS_PBC",
strlen("WPS_PBC"),buf,&resp_len,wpa_ctrl_msg_cb);if(-2==ret){log_message(LOG_FILE,"WPS_CTRL: WPS_PBC command timeout!\n");return-2;}else if(0!=ret){log_message(LOG_FILE,"WPS_CTRL: WPS_PBC command error!\n");return-1;}drawLine1("WPS: Connecting device.");log_message(LOG_FILE,"WPS_CTRL: WPS button pushed, UI action...\n");exit=false;int _count=0;do{while(wpa_ctrl_pending(ctrl_conn)){resp_len=WPS_BUF_SIZE-1;if(0==wpa_ctrl_recv(ctrl_conn,buf,&resp_len)){buf[resp_len]='\0';if(NULL!=strstr(buf,"WPS-REG-SUCCESS")){log_message(LOG_FILE,"WPS_CTRL: Register success, UI action...\n");drawLine1("New device connected");sleep(3);}else if(NULL!=strstr(buf,"WPS-EVENT-TIMEOUT")){log_message(LOG_FILE,"WPS_CTRL: WPS mode timeout, UI action...\n");drawLine1("WPS : No device found");if(auth_changed){
wps_restore_auth_config(&wpa_info);system("/etc/init.d/br_wifi restart");}sleep(3);;}else{continue;}exit=true;break;}else{log_message(LOG_FILE,"WPS_CTRL: receive event failed!\n");exit=true;break;}}}while(!exit);wpa_ctrl_detach(ctrl_conn);wpa_ctrl_close(ctrl_conn);ctrl_conn=NULL;return 0;}void getPRVersion(){FILE*pp;if((pp=popen("cat /etc/BR_version","r"))==NULL){printf("popen() error!\n");pclose(pp);return;}fgets(g_pr_version,9,pp);pclose(pp);}int main(){daemonize();initshmem();initLCD();g_screen_id=1;int _font_size=18;g_isRunUpdate=1;initKeyEvent();char outbuf[MAX_TEXT_LEN];int _isCharging=0;struct timespec ts;sem_init(&g_update_sem,0,0);pthread_t thread_id[2];pthread_create(&thread_id[0],NULL,(void*)keyevent_task,NULL);pthread_create(&thread_id[1],NULL,(void*)Timer_handle,NULL);system(
"/usr/bin/rcmdc -c 'sim.info' &");system("/usr/bin/rcmdc -c 'network.connect_status' &");int n=0;while(g_isRunUpdate){if(g_isSleepMode==1){reset_bar();drawLine1("Sleeping...Zzz");sem_wait(&g_update_sem);continue;}if(all_info->u_battery.voltage<3.6)_isCharging=1;else _isCharging=0;if(_isCharging==1){if(g_lcd_dim_half==-1||g_lcd_off==-1){system("echo 0 > /sys/class/graphics/fb0/blank");system("echo 128 > /sys/class/backlight/mxc_slcdc_bl.0/brightness");}initLCDTime();reset_bar();drawLine1("Empty Battery.");ts.tv_sec=time(NULL)+1;ts.tv_nsec=0;sem_timedwait(&g_update_sem,&ts);continue;}if(g_isUpdatingFW==1||g_isStartResetToDefault>1){ts.tv_sec=time(NULL)+1;ts.tv_nsec=0;sem_timedwait(&g_update_sem,&ts);continue;}if(g_lcd_off<0){sem_wait(&g_update_sem);if(g_isRunUpdate==0)break;}++n;if(n>=5){if
(all_info->u_threeG_info.RAT==NO_SRV)system("/usr/bin/rcmdc -c 'network.status' &");if(strcmp(all_info->u_threeG_info.fw_version,"")==0)system("/usr/bin/rcmdc -c 'bl.version' &");n=0;}draw_bar(all_info);if(all_info->u_threeG_info.PIN_status==PIN_ENABLE){drawLine1("PIN enabled act via web.");ts.tv_sec=time(NULL)+1;ts.tv_nsec=0;sem_timedwait(&g_update_sem,&ts);continue;}else if(all_info->u_threeG_info.PIN_status==PIN_ERROR){drawLine1("Read SIM fail.");ts.tv_sec=time(NULL)+1;ts.tv_nsec=0;sem_timedwait(&g_update_sem,&ts);continue;}else if(all_info->u_threeG_info.PIN_status==PIN_BLOCKed){drawLine1("PIN Block.");ts.tv_sec=time(NULL)+1;ts.tv_nsec=0;sem_timedwait(&g_update_sem,&ts);continue;}else if(all_info->u_threeG_info.PIN_status==PIN_INVALID){drawLine1("Invalid SIM.");ts.tv_sec=time(NULL)+1;
ts.tv_nsec=0;sem_timedwait(&g_update_sem,&ts);continue;}switch(g_screen_id){case BR_BASIC:{initTextArea();if(strcmp(all_info->u_threeG_info.OP_Name,"")==0){if(all_info->u_threeG_info.RAT>0){char tmp[9];sprintf(tmp,"%s%s",all_info->u_threeG_info.nwk_mcc,all_info->u_threeG_info.nwk_mnc);Draw_string_line1(tmp,_font_size);}else Draw_string_line1(all_info->u_threeG_info.Tech_name,_font_size);}else Draw_string_line1(all_info->u_threeG_info.OP_Name,_font_size);drawfb();}break;case BR_3G_Status:{initTextArea();Draw_string_line1(all_info->u_threeG_info.Tech_name,_font_size);if(all_info->u_threeG_connect.callstate==Connect)getStringLine(DEFAULT_LANG,"Connected",outbuf);else getStringLine(DEFAULT_LANG,"Disconnected",outbuf);Draw_string_line2(outbuf,_font_size);drawfb();}break;case BR_WiFi_Status:{
initTextArea();char tmp[32];getStringLine(DEFAULT_LANG,"(%d) - SSID :",outbuf);sprintf(tmp,outbuf,all_info->u_wifi.num_sta);Draw_string_line1(tmp,_font_size);Draw_string_line2(all_info->u_wifi.SSID,_font_size);drawfb();}break;case BR_Version:initTextArea();Draw_string_line1(all_info->u_threeG_info.fw_version,_font_size);if(strcmp(g_pr_version,"")==0)getPRVersion();Draw_string_line2(g_pr_version,_font_size);drawfb();break;case BR_WPS_Fun:{initTextArea();getStringLine(DEFAULT_LANG,"WPS on:press 5s WPS key",outbuf);Draw_string_line1(outbuf,_font_size);}drawfb();break;}ts.tv_sec=time(NULL)+1;ts.tv_nsec=0;sem_timedwait(&g_update_sem,&ts);if(g_wps_enable_time==0){if(all_info->u_wifi.active!=1){drawLine1("Starting WLAN.");system("/tmp/ap_run");draw_bar(all_info);}char log[256];sprintf(log,
"Started WPS : %d \n",g_wps_enable_time);log_message(LOG_FILE,log);wps_start();g_wps_enable_time=WPS_ENABLE_COUNT_TIME;}else if(g_isWiFiSwitch){g_isWiFiSwitch=0;if(all_info->u_wifi.active!=1){drawLine1("Starting WLAN");system("/tmp/ap_run");}else{drawLine1("Stopping WLAN");system("/tmp/ap_rm");}}}munmap(fbp,screensize);close(fbfd);memory_close();freefont();return 0;}