#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <linux/fb.h>
#include <sys/mman.h>
#include <sys/ioctl.h>
#include "status_bar.h"
#include "bmp_layout.h"
extern char dot_matrix[128][64];unsigned char cmap_1bpp[2];void init_1bpp_cmap(void){unsigned i;for(i=0;i<2;i++){cmap_1bpp[i]=i;}}void update_1bpp_cmap(bmp_color_table_entry_t*p_color_table){unsigned i;bmp_color_table_entry_t*p_lut=p_color_table;for(i=0;i<2;i++){cmap_1bpp[i]=1*(p_lut[i].blue+p_lut[i].green+p_lut[i].red)/(3*0xFF);}}void draw_1bpp_img_on_8bpp_lcd(unsigned char*img_ptr,unsigned img_width,unsigned img_height,unsigned char*lcd_ptr,unsigned lcd_width,unsigned lcd_height,int x_off_set){long x,img_y,lcd_y;long lcd_index=0,img_index=0;long lw;unsigned char target;lw=(((img_width+7)/8)+3)&~0x3;for(img_y=(img_height-1),lcd_y=0;(img_y>=0)&&(lcd_y<lcd_height);img_y--,lcd_y++){img_index=img_y*(lw*8);lcd_index=lcd_y*lcd_width;for(x=0;(x<img_width)&&(x<lcd_width);x++){target=((img_ptr[
img_index>>3]>>(7-(x&7)))&0x01);dot_matrix[x+1+x_off_set][lcd_y]=cmap_1bpp[target];lcd_index++;img_index++;}}}void draw_8bpp_img_on_8bpp_lcd(unsigned char*img_ptr,unsigned img_width,unsigned img_height,unsigned char*lcd_ptr,unsigned lcd_width,unsigned lcd_height){long x,img_y,lcd_y;long lcd_index=0,img_index=0;for(img_y=img_height,lcd_y=0;(img_y>0)&&(lcd_y<lcd_height);img_y--,lcd_y++){img_index=img_y*img_width;lcd_index=lcd_y*lcd_width;for(x=0;(x<img_width)&&(x<lcd_width);x++){dot_matrix[x][img_y]=img_ptr[img_index];lcd_index++;img_index++;}}}int lcd_display_bitmap(unsigned char*bmp_image,unsigned char*lcd_ptr,unsigned lcd_width,unsigned lcd_height,int x_off_set){bmp_image_t*bmp;unsigned long width;unsigned long height;unsigned short bpp;unsigned long compression;unsigned long data_offset
;unsigned char*dataptr;bmp=(bmp_image_t*)bmp_image;if((bmp->header.signature[0]=='B')&&(bmp->header.signature[1]=='M')){compression=bmp->header.compression;width=bmp->header.width;height=bmp->header.height;bpp=bmp->header.bit_count;data_offset=bmp->header.data_offset;dataptr=(unsigned char*)bmp+data_offset;printf("BMP: compression=%lu, width=%lu, height=%lu, bpp=%lu, data_offset=%lu\r\n",compression,width,height,bpp,bmp->header.data_offset);switch(bpp){case 1:if(data_offset>sizeof(bmp->header))update_1bpp_cmap(bmp->color_table);draw_1bpp_img_on_8bpp_lcd(dataptr,width,height,lcd_ptr,lcd_width,lcd_height,x_off_set);break;case 8:draw_8bpp_img_on_8bpp_lcd(dataptr,width,height,lcd_ptr,lcd_width,lcd_height);break;default:printf("Error: %u bit per pixel not supported by this LCD\r\n",bpp);
return 0;}}else{printf("Error: no valid bmp at %lx\r\n",(unsigned long)bmp);return 0;}return 1;}long doGetFileSize(const char*filePath){long fileLength=0;FILE*fp;if(!(fp=fopen(filePath,"r"))){return-1;}if(fseek(fp,0,SEEK_END)){return-1;}fileLength=ftell(fp);fclose(fp);return fileLength;}void drawblk(char*_file_name,int x_off_set){int bmp_fd=0;long fileLength=0;long nBytes;unsigned char*fbp=0;unsigned char*bmp_image;init_1bpp_cmap();fileLength=doGetFileSize(_file_name);printf("%s:fileLength=%ld.\r\n",_file_name,fileLength);bmp_fd=open(_file_name,O_RDWR);if(bmp_fd<0){printf("Error: cannot open %s.\r\n",_file_name);return;}bmp_image=(unsigned char*)malloc(fileLength);nBytes=read(bmp_fd,(void*)bmp_image,fileLength);if(nBytes>0){lcd_display_bitmap(bmp_image,0,128,64,x_off_set);}free(bmp_image)
;close(bmp_fd);}void drawblk_1(int _param){char fname[30];sprintf(fname,"icons/Signal_%d.bmp",_param);drawblk(fname,0);}void drawblk_2(all_info_t*_all_info){switch(_all_info->u_threeG_info.RAT){case 1:case 2:drawblk("icons/G.bmp",21);break;case 3:{if(_all_info->u_threeG_connect.callstate!=Connect)drawblk("icons/G.bmp",21);else drawblk("icons/E.bmp",21);}break;case 4:drawblk("icons/U.bmp",21);break;case 5:case 6:{if(_all_info->u_threeG_connect.callstate==Connect)drawblk("icons/H.bmp",21);else drawblk("icons/U.bmp",21);}break;case 7:drawblk("icons/L.bmp",21);break;default:break;}}void drawblk_3(int _param){if(_param==1)drawblk("icons/SMS.bmp",21*2);}void drawblk_4(int _param){if(_param==1)drawblk("icons/WiFi_01.bmp",21*3);}void drawblk_5(int _param){if(_param==1)drawblk("icons/Roaming.bmp",
21*4);}void drawblk_6(int _param){char fname[30];sprintf(fname,"icons/Battery_%d.bmp",_param);drawblk(fname,21*5);}void reset_bar(){int x,y;for(y=0;y<20;y++){for(x=0;x<128;x++){dot_matrix[x][y]=0;}}for(x=0;x<128;x++){dot_matrix[x][20]=1;}}void draw_bar(all_info_t*all_info){reset_bar();
#ifdef DEMO_MODE
drawblk_1(5);drawblk_3(1);drawblk_4(1);drawblk_5(1);drawblk_6(5);
#else 
drawblk_1(all_info->u_threeG_connect.signal);drawblk_2(all_info);drawblk_3(all_info->u_threeG_connect.sms);drawblk_4(all_info->u_wifi.active);drawblk_5(all_info->u_threeG_info.roaming);drawblk_6(all_info->u_battery.capacity);
#endif 
}
